name: 'final_project'
version: '1.0'
config-version: 2
profile: 'sergiodelgadosdg'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  final_project:
    staging:
      +schema: PL_STAGING
      +materialized: table

    +meta:
      intermediate:
        +schema: PL_TRANSFORMATION
        +materialized: view

      business:
        +schema: PL_BUSINESS
        +materialized: table
flags:
  require_generic_test_arguments_property: true